[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Important for bigger backend functions (TTS, Paystack)
[functions]
  node_bundler = "esbuild"

# Increase timeout for AI/TTS requests
[functions."*"]
  timeout = 26